### PR TITLE
Add option 'path-type'

### LINKED ISSUE #13: Combine with golang action
How can I combine this action with golang?
The command `go env` works, but `msys2do go env` doesn't.

```
name: msys2 build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-go@v1
      - uses: numworks/setup-msys2@v1

      - uses: actions/checkout@v1

      - run: go env
      - run: msys2do go env

```

```
D:\a\project\project>d:\a\_temp\msys\\msys64\usr\bin\bash.exe -ilc "cd $OLDPWD && go env" 
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash: go: command not found
##[error]Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by 1138-4EB**
Fix #13

In this PR, two procedures to override the default value of `MSYS2_PATH_TYPE` are provided. On the one hand, if users set the environment variable, it is not overwritten. On the other hand, option `pathType` can be used to set the default. Supported values are `strict`, `inherit`, or any other (`minimal`).

Two tests are added to the workflow, one for each procedure.

BTW, `@actions/core` is updated.

### CODE REVIEW

**Comment by Ecco** [comment]
Great, thanks! I think the syntax in the YAML file should rather be `file-type` instead of `fileType`. Just like `runs-on` is not `runsOn`.

**Comment by 1138-4EB** [comment]
> Great, thanks! I think the syntax in the YAML file should rather be `file-type` instead of `fileType`. Just like `runs-on` is not `runsOn`.

Done!

**Comment by Ecco** [comment]
Great, thanks!

**Comment by 1138-4EB** [comment]
@Ecco, would you mind updating `v1`, and optionally releasing a semver tag (https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#versioning), so that this feature and `update` are available?

**Pull request merged**
